protein_uniprot_map:
  WNT2: P09544
  FZD4: Q9ULV1
  WLS: Q5T9L3

arpeggio_results:

  minnesota-november-ten:
    proteins:
      - FZD4
    type: wildType
    selections:
      - /A/485/

  vermont-helium-august:
    proteins:
      - FZD4
    type: mutant
    mutations:
      - L485F
    selections:
      - /A/485/

  three-six-red:
    proteins:
      - WLS
    type: wildType
    selections:
      - /B/234/
      - /B/354/

  september-triple-kitten:
    proteins:
      - WLS
    type: mutant
    mutations:
      - W234C
      - M354T
    selections:
      - /B/234/
      - /B/354/