protein_uniprot_map:
  WNT2: P09544
  FZD4: Q9ULV1
  WLS: Q5T9L3

arpeggio_results:

  6bd4_hydrogenated:
    proteins:
      - FZD4
    type: wildType
    selections:
      - /A/485/
    pdb_id: 6bd4

  L485F_6bd4_hydrogenated:
    proteins:
      - FZD4
    type: mutant
    mutations:
      - L485F
    selections:
      - /A/485/

  7drt_hydrogenated:
    proteins:
      - WLS
    type: wildType
    selections:
      - /A/234/
      - /A/354/
    pdb_id: 7drt

  W234C_7drt_hydrogenated:
    proteins:
      - WLS
    type: mutant
    mutations:
      - W234C
    selections:
      - /A/234/

  M354T_7drt_hydrogenated:
    proteins:
      - WLS
    type: mutant
    mutations:
      - M354T
    selections:
      - /A/354/